import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import Sidebar from "./components/sidebar";
import AnimatedSignInButton from "./components/animatedSignupButton";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Show this when the user is signed out */}
          <SignedOut>
            <header className="flex justify-between items-center p-4 bg-gray-900 text-white shadow-md">
              <h1 className="text-lg font-bold">Finance Manager</h1>
              <AnimatedSignInButton />
            </header>
          </SignedOut>

          {/* Show Sidebar & Content when signed in */}
          <SignedIn>
            <div className="flex">
              <Sidebar />
              <main className="flex-1 p-4">{children}</main>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
